# Generated by Django 4.0.5 on 2022-06-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_suppliers_supplier_contact'),
        ('billing_app', '0002_alter_customerinfo_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='inventory_app.productinfo'),
        ),
    ]
