# Generated by Django 4.0.5 on 2022-06-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
                ('total_quantity_of_products', models.IntegerField()),
                ('total_price_of_products_without_gst', models.FloatField()),
                ('total_price_of_products_with_gst', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('product_price_per_unit', models.FloatField()),
                ('total_product_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.orders')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='inventory_app.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummery',
            fields=[
                ('order_summery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_delivery_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.orders')),
            ],
        ),
    ]
