# Generated by Django 4.0.5 on 2022-06-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_suppliers_supplier_contact'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.productinfo'),
        ),
    ]
