# Generated by Django 4.0.5 on 2022-06-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('gst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gst_no', models.IntegerField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('igst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_contact', models.IntegerField()),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_hsn', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('date_of_manufacturing', models.DateTimeField()),
                ('product_description', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('product_price_without_gst', models.FloatField()),
                ('product_quantity', models.FloatField()),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.gst')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.productcategory')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.suppliers')),
            ],
        ),
    ]
