# Generated by Django 4.0.5 on 2022-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_address',
            field=models.TextField(),
        ),
    ]
