# Generated by Django 4.0.5 on 2022-06-21 11:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_suppliers_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
