# Generated by Django 4.0.5 on 2022-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='current_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='permanent_address',
            field=models.TextField(),
        ),
    ]
