# Generated by Django 4.0.5 on 2022-06-21 11:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userinfo_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
